<?php
Route::set('index.php',function(){
   Index::CreateView('Index');
});
Route::set('projects',function(){
    Projects::CreateView('Projects');
 });
 Route::set('contacts',function(){
    Contacts::CreateView('Contacts');
 });
 Route::set('portfolio',function(){
    Contacts::CreateView('Portfolio');
 });
?>